// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import Handlebars from "handlebars";

Handlebars.registerHelper("capitalize", (function (aString) {
        if (aString !== undefined) {
          if (aString === "") {
            return Js_exn.raiseError("can't capitalize an empty argument");
          } else {
            return Js_string.charAt(0, aString).toUpperCase() + Js_string.substringToEnd(1, aString);
          }
        } else {
          return Js_exn.raiseError("can't capitalize an undefined argument");
        }
      }));

var templateFile = Fs.readFileSync("./src/template.hbs", {
      encoding: "utf8"
    });

var compileTemplate = Handlebars.compile(templateFile);

export {
  templateFile ,
  compileTemplate ,
}
/*  Not a pure module */
