// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var ArgsError = /* @__PURE__ */Caml_exceptions.create("Utils.ArgsError");

var InputFileNotFoundError = /* @__PURE__ */Caml_exceptions.create("Utils.InputFileNotFoundError");

var ValidationError = /* @__PURE__ */Caml_exceptions.create("Utils.ValidationError");

var DereferenceError = /* @__PURE__ */Caml_exceptions.create("Utils.DereferenceError");

export {
  ArgsError ,
  InputFileNotFoundError ,
  ValidationError ,
  DereferenceError ,
}
/* No side effect */
